repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      # ==========================================
      # 10.03.lab02 infra check
      # ==========================================    
      - id: terraform_fmt
        name: "10.03.lab02 Terraform Format"
        files: ^Cloud/Terraform Core/10 배포 자동화/03 품질 게이트 & 브랜치 보호/lab02/infra/.*\.tf$

      - id: terraform_validate
        name: "10.03.lab02 Terraform Validate"
        args:
          - --hook-config=--retry-once-with-cleanup=true
        files: ^Cloud/Terraform Core/10 배포 자동화/03 품질 게이트 & 브랜치 보호/lab02/infra/.*\.tf$

      - id: terraform_tflint
        name: "10.03.lab02 Terraform TFLint"
        args:
          - --args=--recursive
        files: ^Cloud/Terraform Core/10 배포 자동화/03 품질 게이트 & 브랜치 보호/lab02/infra/.*\.tf$

      - id: terraform_tfsec
        name: "10.03.lab02 Terraform tfsec"
        args:
          - --args=--soft-fail
        files: ^Cloud/Terraform Core/10 배포 자동화/03 품질 게이트 & 브랜치 보호/lab02/infra/.*\.tf$

      # ==========================================
      # 10.05.gallery infra check
      # ==========================================    
      - id: terraform_fmt
        name: "10.05.gallery Terraform Format"
        files: ^Cloud/Terraform Core/10 배포 자동화/05 Gallery/infra/.*\.tf$

      - id: terraform_validate
        name: "10.05.gallery Terraform Validate"
        args:
          - --hook-config=--retry-once-with-cleanup=true
        files: ^Cloud/Terraform Core/10 배포 자동화/05 Gallery/infra/.*\.tf$

      - id: terraform_tflint
        name: "10.05.gallery Terraform TFLint"
        args:
          - --args=--recursive
        files: ^Cloud/Terraform Core/10 배포 자동화/05 Gallery/infra/.*\.tf$

      - id: terraform_tfsec
        name: "10.05.gallery Terraform tfsec"
        args:
          - --args=--soft-fail
        files: ^Cloud/Terraform Core/10 배포 자동화/05 Gallery/infra/.*\.tf$